sudo: required
before_install:
  - docker pull selenium/standalone-chrome:3.141.59
services:
  - docker
install:
  - docker-compose build
  - docker-compose up -d
before_script:
  - sleep 60
  - docker-compose exec selenium /bin/bash -c "curl http://localhost:4444/wd/hub/status"
script:
  - sleep 60
  - docker-compose logs checkpages
  - docker-compose logs selenium
after_script:
  - docker-compose stop
  - docker-compose rm -f
notifications:
  email: false
  slack:
    secure: QxAidE0NIMoCtsJeZWgWyNRxh2vzz6UCZBa9pEGhRM2kuIDN5Kp3C3iG+ez2kKWN6wDG8upRZMsGlpXzqte4Hg7EsKS/yxMBfpJi+IQDSB1l1s67sIIdUSz6BUnaKQBGArJXYVehzkR/5I/4SJpzQVgOgifWzVzpELyB7rJgK8KTOyqSgUBGU1BKg2tEd8awQWyXpGPvEIM7MKRKqwMZABCf0orvuDGeesLJK1Qj4nyPSgePilTWOPKvJ8iwVFmSyxxlz0kRl4EiLilERJ0sxDir1zj/esrPNQbNLrFASbqYggpe+A1wzWvxxJArYhtTpJlP/LUU7fBeIyMHkpDmXvo1tNlF6AfqlLXRsQF1QcQhv6mJ8K4vgUeECpSecXRZl+CH49nLZqNVRgxi544hJx8XKJ5y7YRl9mY05tgrojkyBoSWcarrIiiz69uDQYG2SCpH5Ex257XJ1bZD2RnGMX2vJRytTwPY/uqY8q9xRvQPhukszYQXdGWtbKN3VpJnPesPaeuDNdCLnqVmOuOQkWLE44M1ksySgpzaxu7tgvWW4mIi/U7eaajdrWd1edEzzQXeF2JS7U7iv13svgddO6R4hOz/hmqWkcu5kati0OWZfvCe3DQlnZA610zTagUQ+pbdKDr5JZR0k9HbipuJ61qfysoTM66PEuLP3qZ7CKM=
